artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://public.roboflow.com/ds/CiRl7UcAg5?key=U9EfWfZEqD
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  updated_model_path: artifacts/prepare_base_model/base_model_updated.pt
  trained_model_mod: artifacts/prepare_base_model/runs
